<?php 



	$attribute = Mage::getModel('eav/entity_attribute')

                ->loadByCode('catalog_product', 'brand');



$valuesCollection = Mage::getResourceModel('eav/entity_attribute_option_collection')

            ->setAttributeFilter($attribute->getData('attribute_id'))

            ->setStoreFilter(0, false);



$preparedManufacturers = array();            

foreach($valuesCollection as $value) {

    $preparedManufacturers[$value->getOptionId()] = $value->getValue();

}   
?>


<table class="brand_x">
<tr>
<?php 
$r=1;  
foreach($preparedManufacturers as $optionId => $value) 
{ ?>

        
<td class="brand_td"><a href="<?php echo 'http://www.tooldex.com/catalogsearch/advanced/result/?brand[]='.$optionId; ?>"><?php echo $value;  ?></a></td>
		
<?php if($r%5=='0') { ?> </tr> <?php } $r++; }   ?>
</tr>
</table>
 
 
  
